@extends('layouts.app')

@section('title', 'Dashboard')

@push('styles')
 

@endpush




@push('scripts')


<script src="{{ asset('assets/vendors/fullcalendar/fullcalendar.min.js') }}"></script>




  @section('content')

    <div class="calendar-app">
      <!-- Sidebar -->
       

        <button class="calendar-sidebar-toggle" id="calendarSidebarToggle" aria-label="Toggle calendar sidebar">
          <i class="bi bi-calendar3"></i>
          <span>Mini Calendar &amp; Events</span>
        </button>

        <div class="calendar-sidebar-overlay" id="calendarSidebarOverlay"></div>


        <div class="calendar-sidebar" id="calendarSidebar">
          <!-- Create Event Button -->
          <button class="btn btn-primary w-100 mb-3" data-bs-toggle="modal" data-bs-target="#createEventModal">
            <i class="bi bi-plus-lg me-2"></i> Create Event
          </button>

          <div class="card">
            <div class="card-body mini-calendar">
              <div class="mini-calendar-header">
                <span class="mini-calendar-title" id="miniCalendarTitle">January 2026</span>
                <div class="mini-calendar-nav">
                  <button id="miniCalendarPrev">
                    <i class="bi bi-chevron-left"></i>
                  </button>
                  <button id="miniCalendarNext">
                    <i class="bi bi-chevron-right"></i>
                  </button>
                </div>
              </div>
              <div class="mini-calendar-grid" id="miniCalendarGrid">
                <!-- Days will be generated by JS -->
              </div>
            </div>
          </div>

          <!-- Upcoming Events -->
          <div class="card mb-3">
            <div class="card-header">Upcoming Events</div>
            <div class="card-body p-2" id="upcomingEvents">
              <!-- JS will populate this -->
            </div>
          </div>
        </div>

       


      <!-- Main Calendar -->
      <div class="flex-grow-1 p-3">
        <div id="calendar"></div>
      </div>




    </div>

    @include('calendar.partials.modals') <!-- Include your modals here -->

  @endsection

  @push('scripts')
 
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/index.global.min.js"></script>

    <script>



      document.addEventListener('DOMContentLoaded', function () {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').content;

        const calendarEl = document.getElementById('calendar');
        const upcomingEl = document.getElementById('upcomingEvents');

        const calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'dayGridMonth',
          height: 750,
          headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay'
          },
          selectable: true,
          editable: true,
          events: "{{ route('events.index') }}",

          select: function (info) {
            // Open create modal and prefill date
            const modal = new bootstrap.Modal(document.getElementById('createEventModal'));
            document.getElementById('eventDate').value = info.startStr;
            modal.show();
            calendar.unselect();
          },

          eventClick: function (info) {
            const modal = new bootstrap.Modal(document.getElementById('eventDetailsModal'));
            document.getElementById('eventDetailsTitle').innerText = info.event.title;
            document.getElementById('eventDetailsDate').innerText = info.event.start.toLocaleDateString();
            document.getElementById('eventDetailsTime').innerText = info.event.allDay ? 'All Day' : info.event.start.toLocaleTimeString() + ' - ' + info.event.end?.toLocaleTimeString();
            document.getElementById('eventDetailsCategory').className = 'badge bg-' + (info.event.extendedProps.color || 'primary');
            document.getElementById('eventDetailsDescription').innerText = info.event.extendedProps.description || 'No description provided.';

            document.getElementById('deleteEventBtn').onclick = function () {
              if (confirm('Delete this event?')) {
                fetch(`/events/${info.event.id}`, {
                  method: 'DELETE',
                  headers: { 'X-CSRF-TOKEN': csrfToken }
                }).then(() => {
                  info.event.remove();
                  modal.hide();
                });
              }
            };
            modal.show();
          },

          eventDrop: function (info) {
            fetch(`/events/${info.event.id}`, {
              method: 'PUT',
              headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': csrfToken
              },
              body: JSON.stringify({
                start_date: info.event.start.toISOString(),
                end_date: info.event.end ? info.event.end.toISOString() : info.event.start.toISOString()
              })
            });
          }
        });

        calendar.render();

        // Handle create modal save button
        document.getElementById('saveEventBtn').onclick = function () {
          const title = document.getElementById('eventTitle').value;
          const start_date = document.getElementById('eventDate').value;
          const time = document.getElementById('eventTime').value;
          const color = document.getElementById('eventCategory').value;
          const description = document.getElementById('eventDescription').value;
          const all_day = document.getElementById('eventAllDay').checked;

          if (!title) return alert('Title required');

          fetch("{{ route('events.store') }}", {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'X-CSRF-TOKEN': csrfToken
            },
            body: JSON.stringify({
              title, start_date, time, color, description, all_day
            })
          }).then(res => res.json()).then(data => {
            if (data.success) {
              calendar.refetchEvents();
              bootstrap.Modal.getInstance(document.getElementById('createEventModal')).hide();
            }
          });
        };
      });
    </script>
  @endpush



@endpush